trajectory:
  loop: true
  fly_now: true
  dynamic_uav_name: false
  uavs:
    uav1:
      filename: "sample_trajectories/trajectory1.txt"
      offset: [-5.0, 0.0, 2.0, 0.0]      # [x, y, z, heading]
    uav2: 
      filename: "sample_trajectories/trajectory2.txt"
      offset: [0.0, 0.0, 2.0, 0.0]      # [x, y, z, heading]
