# general parameters
min_onboard_detection_count: 2
min_external_detection_count: 1
buffer_length: 10
transform_lookup_timeout: 0.5 # seconds
message_throttle_period: 1.0 # seconds
# after no onboard detections are associated to a track for this amount of time,
# it is no longer considered to be tracked onboard and external detections can
# again be associated to it
tracking_timeout: 2.0 # seconds
# if there is no current track, publish a message with all zeros to reset the Rviz marker
no_track:
  publish_empty: true
  empty_state: [0.0, 0.0, -20.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  empty_covariance_value: 0.0

# used just for visualization
prediction:
  horizon: 2.0 # seconds
  sampling_period: 0.5 # seconds

# parameters of input pointcloud filtering
input_filter:
  # points inside the box, defined by *uav_exclude_box*, relative to the sensor, are discarded
  # this is used to filter out the MAV itself from the pointcloud
  exclude_box:
    offset: # offset of the box center relative to the sensor origin
      x: 0.09 # meters
      y: 0.0 # meters
      z: -0.75 # meters
    size:
      x: 2.0 # meters
      y: 2.0 # meters
      z: 1.5 # meters

# parameters of the system model, used for the LKF
lkf:
  # the process noise covariance matrix
  Q:
    position: 0.01
    velocity: 0.2
    acceleration: 0.3
  # the state uncertainty covariance matrix
  P:
    # the "radius" of P is obtained as radius_multiplier*cbrt(P)
    radius:
      multiplier: 1.5
      # the minimal radius used for the association
      min: 2.5 # metres
      # if the radius of P gets larger than this value,
      # the track will be deleted
      max: 5.0 # metres
    # these values will be used for initialization of P0
    init:
      position: 0.3
      velocity: 1.0
      acceleration: 1.0
  # the measurement uncertainty covariance matrix
  R:
    coeff: 0.1

# parameters for the cluster-to-track association algorithm
association:
  clustering_tolerance: 1.0 # metres
  # used to filter out invalid clusters
  cluster:
    min_points: 1
    max_points: 262144
    max_size: 1.0 # metres
    min_background_dist: 1.0 # metres
